package defpackage;

import com.google.android.youtube.R;
import java.util.EnumMap;

/* renamed from: fhs */
public final class fhs implements akvp {
    private final EnumMap a;

    public fhs() {
        EnumMap enumMap = new EnumMap(arwh.class);
        enumMap.put(arwh.ACCOUNT_BOX, Integer.valueOf(R.drawable.quantum_ic_account_box_grey600_24));
        enumMap.put(arwh.ACCOUNT_LINKED, Integer.valueOf(R.drawable.ic_account_linked));
        enumMap.put(arwh.ACCOUNT_SOME_LINKED, Integer.valueOf(R.drawable.ic_account_some_linked));
        enumMap.put(arwh.ACCOUNT_UNLINKED, Integer.valueOf(R.drawable.ic_account_unlinked));
        enumMap.put(arwh.ADD, Integer.valueOf(R.drawable.quantum_ic_add_white_36));
        enumMap.put(arwh.ADD_SMALL, Integer.valueOf(R.drawable.quantum_ic_add_googblue_18));
        enumMap.put(arwh.ADD_CIRCLE, Integer.valueOf(R.drawable.quantum_ic_add_circle_grey600_18));
        enumMap.put(arwh.ADD_FRIEND, Integer.valueOf(R.drawable.quantum_ic_person_add_googblue_24));
        enumMap.put(arwh.ADD_TO_PLAYLIST, Integer.valueOf(R.drawable.ic_overflow_addtoplaylist));
        enumMap.put(arwh.ADD_TO_WATCH_LATER, Integer.valueOf(R.drawable.quantum_ic_watch_later_grey600_24));
        enumMap.put(arwh.ANDROID_PHONE, Integer.valueOf(R.drawable.quantum_ic_phone_android_grey600_24));
        enumMap.put(arwh.APP_INSTALL, Integer.valueOf(R.drawable.ic_app_install_white_24));
        enumMap.put(arwh.ARROW_DROP_DOWN, Integer.valueOf(R.drawable.quantum_ic_arrow_drop_down_grey600_24));
        enumMap.put(arwh.ARROW_DROP_UP, Integer.valueOf(R.drawable.quantum_ic_arrow_drop_up_grey600_24));
        enumMap.put(arwh.ASSESSMENT, Integer.valueOf(R.drawable.quantum_ic_assessment_grey600_24));
        enumMap.put(arwh.BACK_LIGHT, Integer.valueOf(R.drawable.quantum_ic_arrow_back_white_24));
        enumMap.put(arwh.BACKGROUND_SIGNED_OUT, Integer.valueOf(R.drawable.img_signed_out));
        enumMap.put(arwh.BACKGROUND_SUBSCRIBE, Integer.valueOf(R.drawable.img_no_subscriptions));
        enumMap.put(arwh.BACKGROUND_SUBSCRIBE_TRANSPARENT, Integer.valueOf(R.drawable.img_no_subscriptions_transparent));
        enumMap.put(arwh.BREAKING_NEWS, Integer.valueOf(R.drawable.ic_breaking_news));
        enumMap.put(arwh.BUY_DATA, Integer.valueOf(R.drawable.quantum_ic_add_shopping_cart_grey600_24));
        enumMap.put(arwh.CANCEL_FRIEND_INVITE, Integer.valueOf(R.drawable.quantum_ic_clear_grey600_24));
        enumMap.put(arwh.CAPTIONS, Integer.valueOf(R.drawable.quantum_ic_closed_caption_grey600_24));
        arwh arwh = arwh.CHANNEL_NOTIFICATION_PREFERENCE_OFF;
        Integer valueOf = Integer.valueOf(R.drawable.quantum_ic_notifications_none_grey600_24);
        enumMap.put(arwh, valueOf);
        arwh = arwh.CHANNEL_NOTIFICATION_PREFERENCE_ON;
        Integer valueOf2 = Integer.valueOf(R.drawable.quantum_ic_notifications_active_grey600_24);
        enumMap.put(arwh, valueOf2);
        enumMap.put(arwh.CHAT, Integer.valueOf(R.drawable.quantum_ic_chat_white_24));
        enumMap.put(arwh.CHAT_OFF, Integer.valueOf(R.drawable.quantum_ic_speaker_notes_off_white_24));
        enumMap.put(arwh.CHECK, Integer.valueOf(R.drawable.quantum_ic_check_white_24));
        enumMap.put(arwh.CHECK_BOX_BLUE, Integer.valueOf(R.drawable.quantum_ic_check_box_googblue_24));
        enumMap.put(arwh.CHECK_BOX_OUTLINE_GREY, Integer.valueOf(R.drawable.quantum_ic_check_box_outline_blank_grey600_24));
        enumMap.put(arwh.CHECK_CIRCLE_THICK, Integer.valueOf(R.drawable.quantum_ic_check_circle_grey600_24));
        enumMap.put(arwh.CHEVRON_RIGHT, Integer.valueOf(R.drawable.quantum_ic_chevron_right_white_36));
        enumMap.put(arwh.CHEVRON_RIGHT_GREY, Integer.valueOf(R.drawable.quantum_ic_chevron_right_grey600_24));
        enumMap.put(arwh.CLOSE, Integer.valueOf(R.drawable.quantum_ic_close_white_24));
        enumMap.put(arwh.CLOSE_LIGHT, Integer.valueOf(R.drawable.quantum_ic_close_grey600_18));
        enumMap.put(arwh.COLLAPSE, Integer.valueOf(R.drawable.ic_drawer_collapse));
        enumMap.put(arwh.COMMENT, Integer.valueOf(R.drawable.quantum_ic_comment_grey600_24));
        enumMap.put(arwh.COURSE, Integer.valueOf(R.drawable.quantum_ic_lightbulb_grey600_24));
        enumMap.put(arwh.CREATOR_STUDIO, Integer.valueOf(R.drawable.quantum_ic_youtube_creator_grey600_24));
        enumMap.put(arwh.CREATION_ENTRY, Integer.valueOf(R.drawable.ic_yt_create_add));
        enumMap.put(arwh.DARK_THEME, Integer.valueOf(R.drawable.quantum_ic_brightness_4_grey600_24));
        enumMap.put(arwh.DARK_THEME_LARGE, Integer.valueOf(R.drawable.quantum_ic_brightness_4_grey600_48));
        enumMap.put(arwh.DELETE, Integer.valueOf(R.drawable.quantum_ic_delete_grey600_24));
        enumMap.put(arwh.DELETE_LIGHT, Integer.valueOf(R.drawable.quantum_ic_delete_white_24));
        enumMap.put(arwh.DISLIKE, Integer.valueOf(R.drawable.ic_thumb_down_24));
        enumMap.put(arwh.DISLIKE_SELECTED, Integer.valueOf(R.drawable.ic_thumb_down_24_selected));
        enumMap.put(arwh.DISMISSAL, Integer.valueOf(R.drawable.quantum_ic_close_grey600_24));
        enumMap.put(arwh.EMPTY_SEARCH, Integer.valueOf(R.drawable.ic_search_no_content));
        enumMap.put(arwh.EMPTY_STATE_CREATE_VIDEO, Integer.valueOf(R.drawable.ic_videocam_grey_60));
        enumMap.put(arwh.EMPTY_STATE_NO_CONTENT, Integer.valueOf(R.drawable.ic_account_circle_grey_60));
        enumMap.put(arwh.EMPTY_STATE_ORGANIZE_CHANNEL, Integer.valueOf(R.drawable.ic_organize_grey_60));
        enumMap.put(arwh.EMPTY_STATE_PRIVATE_CONTENT, Integer.valueOf(R.drawable.ic_lock_outline_60));
        enumMap.put(arwh.EMPTY_STATE_WATCH_LATER, Integer.valueOf(R.drawable.quantum_ic_watch_later_grey600_48));
        arwh = arwh.ERROR_OUTLINE;
        Integer valueOf3 = Integer.valueOf(R.drawable.quantum_ic_error_white_24);
        enumMap.put(arwh, valueOf3);
        enumMap.put(arwh.ERROR_WHITE, valueOf3);
        enumMap.put(arwh.EXIT_TO_APP, Integer.valueOf(R.drawable.quantum_ic_exit_to_app_grey600_24));
        enumMap.put(arwh.EXPAND, Integer.valueOf(R.drawable.ic_drawer_expand));
        enumMap.put(arwh.EXTERNAL_LINK, Integer.valueOf(R.drawable.quantum_ic_open_in_new_white_36));
        enumMap.put(arwh.FAB_CAMERA, Integer.valueOf(R.drawable.quantum_ic_videocam_white_24));
        enumMap.put(arwh.FAB_UPLOAD, Integer.valueOf(R.drawable.ic_fab_upload));
        enumMap.put(arwh.FEEDBACK, Integer.valueOf(R.drawable.quantum_ic_feedback_grey600_24));
        enumMap.put(arwh.FILTER, Integer.valueOf(R.drawable.quantum_ic_filter_list_black_24));
        enumMap.put(arwh.FLAG, Integer.valueOf(R.drawable.quantum_ic_flag_grey600_24));
        enumMap.put(arwh.FULL_HEART, Integer.valueOf(R.drawable.quantum_ic_favorite_grey600_24));
        enumMap.put(arwh.HAPPY, Integer.valueOf(R.drawable.quantum_ic_sentiment_satisfied_grey600_24));
        enumMap.put(arwh.HELP, Integer.valueOf(R.drawable.quantum_ic_help_grey600_24));
        arwh = arwh.HIDE;
        valueOf3 = Integer.valueOf(R.drawable.ic_overflow_not_interested);
        enumMap.put(arwh, valueOf3);
        enumMap.put(arwh.IMPORT_CONTACTS, Integer.valueOf(R.drawable.quantum_ic_import_contacts_grey600_24));
        enumMap.put(arwh.INCOGNITO_CIRCLE, Integer.valueOf(R.drawable.ic_incognito_circle_dark_24));
        enumMap.put(arwh.INFO, Integer.valueOf(R.drawable.quantum_ic_info_grey600_24));
        enumMap.put(arwh.INFO_OUTLINE, Integer.valueOf(R.drawable.quantum_ic_info_outline_white_24));
        enumMap.put(arwh.INVITE_ONLY_MODE, Integer.valueOf(R.drawable.invite_only_chat_locked_filled_48dp));
        enumMap.put(arwh.INVITE_ONLY_MODE_OFF, Integer.valueOf(R.drawable.invite_only_chat_unlocked_filled_48dp));
        enumMap.put(arwh.KEYBOARD_ARROW_LEFT, Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_left_white_24));
        enumMap.put(arwh.KEYBOARD_ARROW_RIGHT, Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_right_white_24));
        enumMap.put(arwh.KEYBOARD_ARROW_UP, Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_up_white_24));
        enumMap.put(arwh.KEYBOARD_ARROW_DOWN, Integer.valueOf(R.drawable.quantum_ic_keyboard_arrow_down_white_24));
        enumMap.put(arwh.LANGUAGE, Integer.valueOf(R.drawable.quantum_ic_language_grey600_24));
        enumMap.put(arwh.LIKE, Integer.valueOf(R.drawable.ic_thumb_up_24));
        enumMap.put(arwh.LIKE_SELECTED, Integer.valueOf(R.drawable.ic_thumb_up_24_selected));
        enumMap.put(arwh.LIKES_PLAYLIST, Integer.valueOf(R.drawable.ic_drawer_likes_playlist_normal));
        enumMap.put(arwh.LINK, Integer.valueOf(R.drawable.quantum_ic_link_grey600_24));
        enumMap.put(arwh.LIVE, Integer.valueOf(R.drawable.quantum_ic_youtube_live_grey600_24));
        enumMap.put(arwh.LOCAL_SHIPPING, Integer.valueOf(R.drawable.quantum_ic_local_shipping_white_24));
        enumMap.put(arwh.LOCATION_ON, Integer.valueOf(R.drawable.quantum_ic_location_on_white_24));
        enumMap.put(arwh.LOCATION_PIN, Integer.valueOf(R.drawable.quantum_ic_location_on_grey600_24));
        arwh = arwh.LOCK;
        Integer valueOf4 = Integer.valueOf(R.drawable.quantum_ic_lock_grey600_24);
        enumMap.put(arwh, valueOf4);
        enumMap.put(arwh.MEH, Integer.valueOf(R.drawable.quantum_ic_sentiment_neutral_grey600_24));
        enumMap.put(arwh.MEMBER, Integer.valueOf(R.drawable.ic_member_full_green_16));
        enumMap.put(arwh.MEMBERS_ONLY_MODE, Integer.valueOf(R.drawable.ic_sponsorsmode_enabled_dark_48));
        arwh = arwh.MEMBERS_ONLY_MODE_OFF;
        Integer valueOf5 = Integer.valueOf(R.drawable.quantum_ic_chat_black_48);
        enumMap.put(arwh, valueOf5);
        arwh = arwh.MEMBERSHIP_CANCELED;
        Integer valueOf6 = Integer.valueOf(R.drawable.quantum_ic_stars_grey600_36);
        enumMap.put(arwh, valueOf6);
        enumMap.put(arwh.MEMBERSHIP_MANAGE, valueOf6);
        enumMap.put(arwh.MEMBERSHIP_OFFER, valueOf6);
        enumMap.put(arwh.MEMBERSHIP_POST_PURCHASE, valueOf6);
        enumMap.put(arwh.MEMBERSHIP_PURCHASED, valueOf6);
        enumMap.put(arwh.MIX, Integer.valueOf(R.drawable.ic_drawer_mix_normal));
        enumMap.put(arwh.MODERATOR, Integer.valueOf(R.drawable.ic_moderator_blue_16));
        enumMap.put(arwh.MONETIZATION_ON, Integer.valueOf(R.drawable.quantum_ic_monetization_on_grey600_24));
        enumMap.put(arwh.MONEY_FILL, Integer.valueOf(R.drawable.ic_money_fill_24));
        enumMap.put(arwh.MORE_LIKE_THIS, Integer.valueOf(R.drawable.quantum_ic_auto_awesome_motion_grey600_24));
        enumMap.put(arwh.MORE_HORIZ_LIGHT, Integer.valueOf(R.drawable.quantum_ic_more_horiz_grey600_24));
        enumMap.put(arwh.MOVIES, Integer.valueOf(R.drawable.quantum_ic_local_movies_grey600_24));
        enumMap.put(arwh.MOVIES_BLUE, Integer.valueOf(R.drawable.quantum_ic_theaters_googblue_48));
        arwh = arwh.MY_VIDEOS_ZERO_STATE;
        Integer valueOf7 = Integer.valueOf(R.drawable.videos_empty_zero_state);
        enumMap.put(arwh, valueOf7);
        enumMap.put(arwh.NO_CONVERSATIONS, Integer.valueOf(R.drawable.img_no_conversations));
        enumMap.put(arwh.NOT_INTERESTED, Integer.valueOf(R.drawable.quantum_ic_not_interested_white_24));
        arwh = arwh.NOTIFICATIONS;
        Integer valueOf8 = Integer.valueOf(R.drawable.quantum_ic_notifications_grey600_24);
        enumMap.put(arwh, valueOf8);
        enumMap.put(arwh.NOTIFICATIONS_ACTIVE, valueOf2);
        enumMap.put(arwh.NOTIFICATIONS_DONE_CHECKMARK, Integer.valueOf(R.drawable.quantum_ic_done_grey600_24));
        enumMap.put(arwh.NOTIFICATIONS_INBOX, Integer.valueOf(R.drawable.ic_drawer_notifications_inbox_normal));
        enumMap.put(arwh.NOTIFICATIONS_NONE, valueOf);
        enumMap.put(arwh.NOTIFICATIONS_OCCASIONAL, Integer.valueOf(R.drawable.ic_notifications_half_bell_grey600_24));
        enumMap.put(arwh.NOTIFICATIONS_OFF, Integer.valueOf(R.drawable.ic_notifications_off_grey600_24));
        enumMap.put(arwh.OFFICIAL_ARTIST_BADGE, Integer.valueOf(R.drawable.quantum_ic_music_note_black_24));
        arwh = arwh.OFFLINE;
        valueOf = Integer.valueOf(R.drawable.ic_drawer_offline_normal);
        enumMap.put(arwh, valueOf);
        enumMap.put(arwh.OFFLINE_CLOUD, Integer.valueOf(R.drawable.ic_offline_cloud));
        enumMap.put(arwh.OFFLINE_COMMUTE, Integer.valueOf(R.drawable.ic_offline_commute));
        enumMap.put(arwh.OFFLINE_DOWNLOAD, valueOf);
        enumMap.put(arwh.OFFLINE_NO_CONTENT, Integer.valueOf(R.drawable.ic_offline_no_content));
        enumMap.put(arwh.OFFLINE_NO_CONTENT_UPSIDE_DOWN, Integer.valueOf(R.drawable.ic_offline_no_content_upside_down));
        enumMap.put(arwh.OPEN_IN_NEW, Integer.valueOf(R.drawable.quantum_ic_open_in_new_grey600_12));
        enumMap.put(arwh.OWNER, Integer.valueOf(R.drawable.ic_crown_orange_16));
        enumMap.put(arwh.PHONE, Integer.valueOf(R.drawable.ic_call));
        enumMap.put(arwh.PHOTO_CAMERA, Integer.valueOf(R.drawable.quantum_ic_photo_camera_grey600_24));
        enumMap.put(arwh.PHOTO_LIBRARY, Integer.valueOf(R.drawable.quantum_ic_photo_library_grey600_24));
        enumMap.put(arwh.PIVOT_HOME, Integer.valueOf(R.drawable.ic_home));
        enumMap.put(arwh.PIVOT_HOME_GREY, Integer.valueOf(R.drawable.quantum_ic_home_grey600_24));
        enumMap.put(arwh.PIVOT_LIBRARY, Integer.valueOf(R.drawable.ic_library));
        enumMap.put(arwh.PIVOT_PREMIER, Integer.valueOf(R.drawable.ic_premier));
        enumMap.put(arwh.PIVOT_REWIND, Integer.valueOf(R.drawable.ic_rewind));
        enumMap.put(arwh.PIVOT_SHARED, Integer.valueOf(R.drawable.ic_social));
        enumMap.put(arwh.PIVOT_SUBSCRIPTIONS, Integer.valueOf(R.drawable.ic_subscriptions));
        arwh = arwh.PIVOT_TRENDING;
        valueOf = Integer.valueOf(R.drawable.ic_trending);
        enumMap.put(arwh, valueOf);
        enumMap.put(arwh.PLAY_ARROW, Integer.valueOf(R.drawable.quantum_ic_play_arrow_white_24));
        enumMap.put(arwh.PLAY_ARROW_BLACK, Integer.valueOf(R.drawable.quantum_ic_play_arrow_black_24));
        enumMap.put(arwh.PLAY_ARROW_OVERLAY, Integer.valueOf(R.drawable.ic_vidcontrol_pause_play_11));
        enumMap.put(arwh.PLAY_DISABLED, Integer.valueOf(R.drawable.quantum_ic_play_disabled_white_24));
        enumMap.put(arwh.PLAYLIST_ADD_CHECK, Integer.valueOf(R.drawable.quantum_ic_playlist_add_check_grey600_24));
        enumMap.put(arwh.PLAYLIST_PLAY, Integer.valueOf(R.drawable.quantum_ic_playlist_play_grey600_24));
        enumMap.put(arwh.PLAYLIST_NOTIFICATION_PREFERENCE_OFF, Integer.valueOf(R.drawable.channel_notification_preferences_off));
        enumMap.put(arwh.PLAYLIST_NOTIFICATION_PREFERENCE_ON, Integer.valueOf(R.drawable.channel_notification_preferences_on));
        enumMap.put(arwh.PLAYLISTS, Integer.valueOf(R.drawable.ic_drawer_playlists_normal));
        enumMap.put(arwh.PRIVACY_INFO, valueOf4);
        enumMap.put(arwh.PRIVACY_PUBLIC, Integer.valueOf(R.drawable.quantum_ic_public_grey600_24));
        enumMap.put(arwh.PRODUCT_FLIGHT, Integer.valueOf(R.drawable.quantum_ic_travel_white_48));
        enumMap.put(arwh.PRODUCT_HOTEL, Integer.valueOf(R.drawable.quantum_ic_hotel_white_48));
        enumMap.put(arwh.PRODUCT_SHOP, Integer.valueOf(R.drawable.quantum_ic_local_offer_white_48));
        enumMap.put(arwh.PURCHASE_SUPER_CHAT, Integer.valueOf(R.drawable.ic_super_chat_24_light));
        enumMap.put(arwh.PURCHASE_SUPER_STICKER, Integer.valueOf(R.drawable.ic_super_sticker_24));
        enumMap.put(arwh.REDEEM_SUPER_CHAT_FREEBIE, Integer.valueOf(R.drawable.ic_super_chat_freebie_20_light));
        enumMap.put(arwh.RESHARE, Integer.valueOf(R.drawable.quantum_ic_googleplus_reshare_grey600_24));
        enumMap.put(arwh.PURCHASES, Integer.valueOf(R.drawable.ic_drawer_purchases_normal));
        enumMap.put(arwh.QUESTION_ANSWER, Integer.valueOf(R.drawable.quantum_ic_question_answer_grey600_24));
        enumMap.put(arwh.RADIO_BUTTON_CHECKED, Integer.valueOf(R.drawable.quantum_ic_radio_button_on_googblue_24));
        enumMap.put(arwh.RADIO_BUTTON_UNCHECKED, Integer.valueOf(R.drawable.quantum_ic_radio_button_unchecked_grey600_24));
        enumMap.put(arwh.REELS_ZERO_STATE, valueOf7);
        enumMap.put(arwh.REFRESH, Integer.valueOf(R.drawable.quantum_ic_refresh_white_24));
        enumMap.put(arwh.REMOVE_FROM_HISTORY, valueOf3);
        enumMap.put(arwh.REPOST, Integer.valueOf(R.drawable.ic_post));
        enumMap.put(arwh.ROTTEN_TOMATOES_CERTIFIED, Integer.valueOf(R.drawable.ic_rotten_tomatoes_certified));
        enumMap.put(arwh.ROTTEN_TOMATOES_FRESH, Integer.valueOf(R.drawable.ic_rotten_tomatoes_fresh));
        enumMap.put(arwh.ROTTEN_TOMATOES_SPLAT, Integer.valueOf(R.drawable.ic_rotten_tomatoes_splat));
        enumMap.put(arwh.SAD, Integer.valueOf(R.drawable.quantum_ic_sentiment_dissatisfied_grey600_24));
        enumMap.put(arwh.SAVE_ALT, Integer.valueOf(R.drawable.quantum_ic_save_alt_googblue_48));
        enumMap.put(arwh.SEARCH, Integer.valueOf(R.drawable.quantum_ic_search_grey600_24));
        enumMap.put(arwh.SETTINGS, Integer.valueOf(R.drawable.quantum_ic_settings_grey600_24));
        enumMap.put(arwh.SHARE, Integer.valueOf(R.drawable.quantum_ic_share_grey600_24));
        enumMap.put(arwh.SHARE_ARROW, Integer.valueOf(R.drawable.ic_share));
        enumMap.put(arwh.SHUFFLE, Integer.valueOf(R.drawable.quantum_ic_shuffle_grey600_48));
        enumMap.put(arwh.SLOW_MODE, Integer.valueOf(R.drawable.ic_slowmode_enabled_dark_48));
        enumMap.put(arwh.SLOW_MODE_OFF, valueOf5);
        enumMap.put(arwh.SMS, Integer.valueOf(R.drawable.ic_textsms));
        enumMap.put(arwh.SORT, Integer.valueOf(R.drawable.quantum_ic_sort_grey600_24));
        enumMap.put(arwh.SPONSORSHIP_STAR, valueOf6);
        arwh = arwh.SPONSORSHIPS;
        valueOf2 = Integer.valueOf(R.drawable.yt_sponsorships);
        enumMap.put(arwh, valueOf2);
        enumMap.put(arwh.PURCHASE_SPONSORSHIP, valueOf2);
        enumMap.put(arwh.STAR, Integer.valueOf(R.drawable.quantum_ic_star_grey600_24));
        enumMap.put(arwh.STAR_BORDER, Integer.valueOf(R.drawable.quantum_ic_star_border_white_24));
        enumMap.put(arwh.STARS, Integer.valueOf(R.drawable.quantum_ic_stars_white_24));
        enumMap.put(arwh.STICKER_LIGHT, Integer.valueOf(R.drawable.quantum_ic_sticker_white_24));
        enumMap.put(arwh.SUBSCRIBED, Integer.valueOf(R.drawable.ic_subscribed));
        enumMap.put(arwh.SUPER_CHAT_FOR_GOOD, Integer.valueOf(R.drawable.quantum_ic_super_chat_for_good_black_24));
        enumMap.put(arwh.SWITCH_ACCOUNTS, Integer.valueOf(R.drawable.ic_switch_account_grey600_24));
        enumMap.put(arwh.TAB_ACCOUNT, Integer.valueOf(R.drawable.ic_tab_account));
        enumMap.put(arwh.TAB_ACTIVITY, valueOf8);
        enumMap.put(arwh.TAB_EXPLORE, Integer.valueOf(R.drawable.quantum_ic_explore_white_24));
        enumMap.put(arwh.TAB_HOME, Integer.valueOf(R.drawable.ic_tab_home));
        enumMap.put(arwh.TAB_INBOX, Integer.valueOf(R.drawable.quantum_ic_email_white_24));
        enumMap.put(arwh.TAB_LIBRARY, Integer.valueOf(R.drawable.ic_tab_library));
        enumMap.put(arwh.TAB_SHARES, Integer.valueOf(R.drawable.ic_tab_share));
        enumMap.put(arwh.TAB_SUBSCRIPTIONS, Integer.valueOf(R.drawable.ic_tab_subscriptions));
        enumMap.put(arwh.TAB_TRENDING, Integer.valueOf(R.drawable.ic_tab_trending));
        enumMap.put(arwh.TAG_FACES, Integer.valueOf(R.drawable.quantum_ic_tag_faces_white_24));
        enumMap.put(arwh.TIMER, Integer.valueOf(R.drawable.quantum_ic_timer_grey600_24));
        enumMap.put(arwh.ACCESS_TIME, Integer.valueOf(R.drawable.quantum_ic_access_time_white_24));
        enumMap.put(arwh.TIP_JAR_LOVE, Integer.valueOf(R.drawable.ic_paypage_avatar));
        enumMap.put(arwh.TRENDING, valueOf);
        enumMap.put(arwh.TUNE, Integer.valueOf(R.drawable.quantum_ic_tune_grey600_24));
        enumMap.put(arwh.TV, Integer.valueOf(R.drawable.quantum_ic_tv_googblue_48));
        enumMap.put(arwh.UNDO, Integer.valueOf(R.drawable.quantum_ic_undo_white_24));
        enumMap.put(arwh.UNLIMITED, Integer.valueOf(R.drawable.quantum_ic_video_youtube_grey600_24));
        enumMap.put(arwh.UNLIMITED_LOGO, Integer.valueOf(R.drawable.yt_subscription_upsell_logo));
        enumMap.put(arwh.UNPLUGGED_LOGO, Integer.valueOf(R.drawable.ic_youtube_u));
        enumMap.put(arwh.UPLOADS, Integer.valueOf(R.drawable.ic_drawer_uploads_normal));
        enumMap.put(arwh.VERIFIED, Integer.valueOf(R.drawable.ic_check_16));
        enumMap.put(arwh.VERY_HAPPY, Integer.valueOf(R.drawable.quantum_ic_sentiment_very_satisfied_grey600_24));
        enumMap.put(arwh.VERY_SAD, Integer.valueOf(R.drawable.quantum_ic_sentiment_very_dissatisfied_grey600_24));
        enumMap.put(arwh.VIDEO_CAMERA, Integer.valueOf(R.drawable.quantum_ic_videocam_grey600_24));
        enumMap.put(arwh.VIDEO_CAMERA_DISABLED, Integer.valueOf(R.drawable.quantum_ic_videocam_off_grey600_24));
        enumMap.put(arwh.VIDEO_LIBRARY_WHITE, Integer.valueOf(R.drawable.quantum_ic_video_library_white_18));
        enumMap.put(arwh.VIDEO_QUALITY, Integer.valueOf(R.drawable.ic_overflow_quality));
        enumMap.put(arwh.VIEW_LIST, Integer.valueOf(R.drawable.ic_view_list_inactive));
        enumMap.put(arwh.VIEW_LIST_DARK, Integer.valueOf(R.drawable.ic_view_list));
        enumMap.put(arwh.VIEW_MODULE, Integer.valueOf(R.drawable.ic_view_module_inactive));
        enumMap.put(arwh.VIEW_MODULE_DARK, Integer.valueOf(R.drawable.ic_view_module));
        enumMap.put(arwh.WARNING, Integer.valueOf(R.drawable.quantum_ic_warning_amber_48));
        enumMap.put(arwh.WATCH_HISTORY, Integer.valueOf(R.drawable.ic_drawer_watch_history_normal));
        enumMap.put(arwh.WATCH_LATER, Integer.valueOf(R.drawable.ic_drawer_watch_later_normal));
        enumMap.put(arwh.WATCH_PARTY, Integer.valueOf(R.drawable.ic_watch_party));
        enumMap.put(arwh.WATCH_RELATED_MIX, Integer.valueOf(R.drawable.ic_mix_28));
        enumMap.put(arwh.WHAT_TO_WATCH, Integer.valueOf(R.drawable.ic_drawer_what_to_watch));
        enumMap.put(arwh.YOUTUBE_MUSIC_BUTTON_RINGO, Integer.valueOf(R.drawable.youtube_music_ringo));
        enumMap.put(arwh.YOUTUBE_MUSIC_LOGO_SHORT, Integer.valueOf(R.drawable.youtube_music_logo_short));
        enumMap.put(arwh.YOUTUBE_PREMIERE_LOGO_SHORT, Integer.valueOf(R.drawable.youtube_premiere_logo_short));
        enumMap.put(arwh.YOUTUBE_RED_LOGO, Integer.valueOf(R.drawable.ytr_header_logo));
        enumMap.put(arwh.YOUTUBE_RED_LOGO_LIGHT, Integer.valueOf(R.drawable.ytr_header_logo_white));
        enumMap.put(arwh.YOUTUBE_RED_LOGO_SHORT, Integer.valueOf(R.drawable.ytr_wordmark_header));
        enumMap.put(arwh.YOUTUBE_RED_ORIGINALS_BUTTON, Integer.valueOf(R.drawable.youtube_red_originals));
        enumMap.put(arwh.YOUTUBE_RED_ORIGINALS_BUTTON_RED, Integer.valueOf(R.drawable.youtube_originals_red));
        enumMap.put(arwh.YOUTUBE_ROUND, Integer.valueOf(R.drawable.product_logo_youtube_color_36));
        enumMap.put(arwh.VOLUME_UP, Integer.valueOf(R.drawable.quantum_ic_volume_up_white_24));
        enumMap.put(arwh.SPEAKER_NOTES, Integer.valueOf(R.drawable.quantum_ic_speaker_notes_white_24));
        enumMap.put(arwh.MOBILE_SCREEN_SHARE, Integer.valueOf(R.drawable.quantum_ic_mobile_screen_share_white_24));
        enumMap.put(arwh.SEARCH_LARGE, Integer.valueOf(R.drawable.ic_search_large));
        this.a = enumMap;
    }

    public final int a(arwh arwh) {
        return this.a.containsKey(arwh) ? ((Integer) this.a.get(arwh)).intValue() : 0;
    }
}
