package defpackage;

import android.content.Context;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

@qlp
/* renamed from: roe */
public final class roe {
    public static final rnr a;
    public static final rnr b;
    public static final rnr c = rnr.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    public static final rnr d;
    public static final rnr e = rnr.a(1, "gads:gestures:task_timeout", 2000);
    public static final rnr f;
    public static final rnr g;
    public static final rnr h;
    public static final rnr i;
    public static final rnr j;
    public static final rnr k;
    public static final rnr l;
    public static final rnr m;
    public static final rnr n;
    public static final rnr o;
    public static final rnr p;
    public static final rnr q;
    public static final rnr r;
    public static final rnr s = rnr.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    private static final rnr t = rnr.a(1, "gads:heap_wastage:bytes", 0);
    private static byte[] u;

    public static void a(Context context) {
        qmi.a(context, new rod(context));
        int intValue = ((Integer) rlj.d().a(t)).intValue();
        if (intValue > 0 && u == null) {
            u = new byte[intValue];
        }
    }

    public static List a() {
        rnx c = rlj.c();
        ArrayList arrayList = new ArrayList();
        for (rnr a : c.b) {
            String str = (String) rlj.d().a(a);
            if (str != null) {
                arrayList.add(str);
            }
        }
        return arrayList;
    }

    static {
        rnr.a(0, "gads:sdk_core_experiment_id");
        rnr.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
        rnr.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
        Boolean valueOf = Boolean.valueOf(false);
        rnr.a(0, "gads:request_builder:singleton_webview", valueOf);
        rnr.a(0, "gads:request_builder:singleton_webview_experiment_id");
        Boolean valueOf2 = Boolean.valueOf(true);
        rnr.a(0, "gads:sdk_use_dynamic_module", valueOf2);
        rnr.a(0, "gads:sdk_use_dynamic_module_experiment_id");
        a = rnr.a(0, "gads:sdk_crash_report_enabled", valueOf);
        rnr.a(0, "gads:report_dynamite_crash_in_background_thread", valueOf);
        b = rnr.a(0, "gads:sdk_crash_report_full_stacktrace", valueOf);
        rnr.a(1, "gads:trapped_exception_sample_rate", 0.01f);
        rnr.a(0, "gads:block_autoclicks_experiment_id");
        rnr.a(0, "gads:spam_app_context:experiment_id");
        rnr.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
        rnr.a(1, "gads:video_exo_player:version", "1");
        rnr.a(1, "gads:video_exo_player:connect_timeout", 8000);
        rnr.a(1, "gads:video_exo_player:read_timeout", 8000);
        rnr.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
        rnr.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
        rnr.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
        rnr.a(0, "gads:video_stream_cache:experiment_id");
        rnr.a(1, "gads:video_stream_cache:limit_count", 5);
        rnr.a(1, "gads:video_stream_cache:limit_space", 8388608);
        rnr.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
        rnr.a(1, "gads:video_stream_cache:limit_time_sec", 300);
        rnr.a(1, "gads:video_stream_cache:notify_interval_millis", 125);
        rnr.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
        rnr.a(0, "gads:video:metric_reporting_enabled", valueOf);
        String str = "";
        rnr.a(1, "gads:video:metric_frame_hash_times", str);
        rnr.a(1, "gads:video:metric_frame_hash_time_leniency", 500);
        rnr.a(1, "gads:video:force_watermark", valueOf);
        rnr.a(1, "gads:video:surface_update_min_spacing_ms", 1000);
        rnr.a(1, "gads:video:spinner:enabled", valueOf);
        rnr.a(1, "gads:video:spinner:scale", 4);
        rnr.a(1, "gads:video:spinner:jank_threshold_ms", 50);
        rnr.a(1, "gads:video:aggressive_media_codec_release", valueOf);
        rnr.a(1, "gads:memory_bundle:debug_info", valueOf);
        rnr.a(1, "gads:video:codec_query_mime_types", str);
        rnr.a(1, "gads:video:codec_query_minimum_version", 16);
        rnr.a(0, "gads:ad_id_app_context:ping_ratio", 0.0f);
        rnr.a(0, "gads:ad_id_use_shared_preference:experiment_id");
        rnr.a(0, "gads:ad_id_use_shared_preference:enabled", valueOf);
        rnr.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0f);
        rnr.a(0, "gads:ad_id_use_persistent_service:enabled", valueOf);
        rnr.a(0, "gads:ad_id:use_ipc:enabled", valueOf);
        rnr.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
        rnr.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
        rnr.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
        rnr.a(1, "gad:mraid:version", "2.0");
        rnr.a(1, "gads:mraid:unload", valueOf);
        rnr.a(0, "gads:enabled_sdk_csi", valueOf);
        rnr.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
        rnr.a(0, "gads:sdk_csi_write_to_file", valueOf);
        rnr.a(0, "gads:enable_content_fetching", valueOf2);
        rnr.a(0, "gads:content_length_weight", 1);
        rnr.a(0, "gads:content_age_weight", 1);
        rnr.a(0, "gads:min_content_len", 11);
        rnr.a(0, "gads:fingerprint_number", 10);
        rnr.a(0, "gads:sleep_sec", 10);
        rnr.a(1, "gads:content_vertical_fingerprint_number", 100);
        rnr.a(1, "gads:content_vertical_fingerprint_bits", 23);
        rnr.a(1, "gads:content_vertical_fingerprint_ngram", 3);
        rnr.a(1, "gads:content_fetch_view_tag_id", "googlebot");
        rnr.a(1, "gads:content_fetch_exclude_view_tag", "none");
        rnr.a(1, "gads:content_fetch_disable_get_title_from_webview", valueOf);
        rnr.a(0, "gads:app_index:without_content_info_present:enabled", valueOf2);
        rnr.a(0, "gads:app_index:timeout_ms", 1000);
        rnr.a(0, "gads:app_index:experiment_id");
        rnr.a(0, "gads:ad_key_enabled", valueOf);
        rnr.a(1, "gads:sai:enabled", valueOf2);
        rnr.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
        rnr.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
        rnr.a(1, "gads:sai:using_macro:enabled", valueOf);
        rnr.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
        rnr.a(1, "gads:sai:timeout_ms", -1);
        rnr.a(1, "gads:sai:scion_thread_pool_size", 5);
        rnr.a(1, "gads:interstitial:app_must_be_foreground:enabled", valueOf);
        rnr.a(0, "gads:webview_cache_version", 0);
        rnr.a(0, "gads:corewebview:adwebview_factory:enable", valueOf);
        rnr.a(0, "gads:corewebview:javascript_engine", valueOf);
        rnr.a(1, "gad:webview:inject_scripts", valueOf);
        rnr.a(0, "gads:webview:permission:disabled", valueOf);
        rnr.b(0, "gads:pan:experiment_id");
        rnr.a(1, "gads:rewarded:adapter_initialization_enabled", valueOf);
        rnr.a(1, "gads:rewarded:adapter_timeout_ms", 20000);
        rnr.a(1, "gads:rewarded:ad_metadata_enabled", valueOf);
        rnr.a(1, "gads:rewarded:ssv_custom_data_enabled", valueOf2);
        rnr.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
        rnr.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
        rnr.a(1, "gads:adid_values_in_adrequest:enabled", valueOf);
        rnr.a(1, "gads:adid_values_in_adrequest:timeout", 2000);
        rnr.a(1, "gads:disable_adid_values_in_ms", valueOf);
        rnr.a(0, "gads:ad_serving:enabled", valueOf2);
        rnr.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
        rnr.a(1, "gads:custom_close_blocking:enabled", valueOf);
        rnr.a(1, "gads:disabling_closable_area:enabled", valueOf);
        rnr.a(1, "gads:impression_optimization_enabled", valueOf);
        rnr.a(1, "gads:banner_ad_pool:schema", "customTargeting");
        rnr.a(1, "gads:banner_ad_pool:max_queues", 3);
        rnr.a(1, "gads:banner_ad_pool:max_pools", 3);
        rnr.a(1, "gads:interstitial_ad_pool:enabled", valueOf);
        rnr.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", valueOf);
        rnr.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
        rnr.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
        rnr.a(1, "gads:interstitial_ad_pool:max_pools", 3);
        rnr.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
        rnr.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
        String str2 = "(?!)";
        rnr.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", str2);
        rnr.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
        rnr.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
        rnr.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0);
        rnr.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0);
        rnr.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0f);
        rnr.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0f);
        rnr.a(0, "gads:debug_logging_feature:enable", valueOf);
        rnr.a(0, "gads:debug_logging_feature:intercept_web_view", valueOf);
        rnr.a(1, "gads:spherical_video:vertex_shader", str);
        rnr.a(1, "gads:spherical_video:fragment_shader", str);
        rnr.a(0, "gads:log:verbose_enabled", valueOf);
        rnr.a(1, "gads:include_local_global_rectangles", valueOf);
        rnr.a(1, "gads:position_watcher:throttle_ms", 200);
        rnr.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000);
        rnr.a(1, "gads:gen204_signals:enabled", valueOf);
        rnr.a(0, "gads:webview:error_reporting_enabled", valueOf);
        rnr.a(0, "gads:adid_reporting:enabled", valueOf);
        rnr.a(0, "gads:ad_settings_page_reporting:enabled", valueOf);
        rnr.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", valueOf);
        rnr.a(1, "gads:rtb_signal_timeout_ms", 1000);
        rnr.a(1, "gads:rtb_cld:enabled", valueOf);
        rnr.a(0, "gads:resolve_future:default_timeout_ms", 30000);
        rnr.a(0, "gads:ad_loader:timeout_ms", 60000);
        rnr.a(0, "gads:rendering:timeout_ms", 60000);
        d = rnr.a(0, "gads:adshield:enable_adshield_instrumentation", valueOf);
        f = rnr.a(1, "gads:gestures:asig:enabled", valueOf);
        rnr.a(1, "gads:gestures:ans:enabled", valueOf);
        g = rnr.a(1, "gads:gestures:tos:enabled", valueOf);
        h = rnr.a(1, "gads:gestures:brt:enabled", valueOf);
        rnr.a(1, "gads:signal:app_permissions:disabled", valueOf);
        i = rnr.a(1, "gads:gestures:inthex:enabled", valueOf);
        j = rnr.a(1, "gads:gestures:hpk:enabled", valueOf2);
        k = rnr.a(1, "gads:gestures:pk", str);
        l = rnr.a(1, "gads:gestures:bs:enabled", valueOf2);
        m = rnr.a(1, "gads:gestures:check_initialization_thread:enabled", valueOf);
        n = rnr.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", valueOf2);
        o = rnr.a(0, "gass:enabled", valueOf2);
        p = rnr.a(0, "gass:enable_int_signal", valueOf2);
        q = rnr.a(0, "gass:enable_ad_attestation_signal", valueOf2);
        rnr.a(0, "gads:adid_notification:first_party_check:enabled", valueOf2);
        rnr.a(1, "gads:sdk_core_constants:experiment_id");
        rnr.a(1, "gads:sdk_core_constants:caps", str);
        rnr.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12));
        rnr.a(0, "gads:js_flags:mf", valueOf);
        rnr.a(1, "gads:js_flags:disable_phenotype", valueOf);
        rnr.a(0, "gads:custom_render:ping_on_ad_rendered", valueOf);
        rnr.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
        rnr.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
        rnr.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
        rnr.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
        rnr.a(1, "gads:native_video_load_timeout", 10);
        rnr.a(1, "gads:omid:native_webview_load_timeout", 2000);
        rnr.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
        rnr.a(1, "gads:enable_store_active_view_state", valueOf);
        rnr.a(1, "gads:enable_singleton_broadcast_receiver", valueOf);
        rnr.a(1, "gads:native:media_view_match_parent:enabled", valueOf);
        rnr.a(1, "gads:native:count_impression_for_assets", valueOf);
        rnr.a(1, "gads:native:custom_one_point_five_click:enable", valueOf2);
        rnr.a(1, "gads:unified_native_ad:enable", valueOf2);
        rnr.a(1, "gads:instream_ad:enabled", valueOf2);
        rnr.a(1, "gads:fluid_ad:use_wrap_content_height", valueOf);
        rnr.a(1, "gads:auto_location_for_coarse_permission", valueOf);
        rnr.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
        rnr.a(1, "gads:auto_location_timeout", 2000);
        rnr.b(1, "gads:auto_location_timeout:experiment_id");
        rnr.a(1, "gads:auto_location_interval", -1);
        rnr.b(1, "gads:auto_location_interval:experiment_id");
        rnr.a(0, "gads:auto_location_interval:without_thread", valueOf2);
        rnr.a(1, "gads:fetch_app_settings_using_cld:enabled", valueOf);
        rnr.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
        rnr.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
        rnr.a(0, "gads:afs:csa:experiment_id");
        rnr.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
        rnr.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
        rnr.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
        rnr.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
        rnr.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
        rnr.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000);
        rnr.a(1, "gads:parental_controls:timeout", 2000);
        rnr.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
        rnr.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000);
        rnr.a(0, "gads:safe_browsing:debug", valueOf);
        rnr.a(1, "gads:cache:ad_request_timeout_millis", 250);
        rnr.a(1, "gads:cache:max_concurrent_downloads", 10);
        rnr.a(1, "gads:cache:javascript_timeout_millis", 5000);
        rnr.a(1, "gads:cache:bind_on_foreground", valueOf);
        rnr.a(1, "gads:cache:bind_on_init", valueOf);
        rnr.a(1, "gads:cache:bind_on_request", valueOf);
        rnr.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
        rnr.a(1, "gads:cache:use_cache_data_source", valueOf);
        rnr.a(1, "gads:cache:connection_per_read", valueOf);
        rnr.a(1, "gads:cache:connection_timeout", 5000);
        rnr.a(1, "gads:cache:read_only_connection_timeout", 5000);
        rnr.a(1, "gads:http_assets_cache:enabled", valueOf);
        rnr.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
        rnr.a(1, "gads:http_assets_cache:time_out", 100);
        rnr.a(1, "gads:chrome_custom_tabs_browser:enabled", valueOf);
        rnr.a(1, "gads:chrome_custom_tabs:disabled", valueOf);
        rnr.a(1, "gads:debug_hold_gesture:enabled", valueOf);
        rnr.a(1, "gads:debug_hold_gesture:time_millis", 2000);
        rnr.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
        rnr.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
        rnr.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
        rnr.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
        rnr.a(1, "gads:drx_debug:timeout_ms", 5000);
        rnr.a(1, "gad:pixel_dp_comparision_multiplier", 1);
        rnr.a(1, "gad:interstitial_for_multi_window", valueOf);
        rnr.a(1, "gad:interstitial_ad_stay_active_in_multi_window", valueOf);
        rnr.a(1, "gad:interstitial_multi_window_method", valueOf);
        rnr.a(1, "gad:interstitial:close_button_padding_dip", 0);
        rnr.a(1, "gads:clearcut_logging:enabled", valueOf);
        rnr.a(1, "gads:clearcut_logging:write_to_file", valueOf);
        rnr.a(0, "gad:force_local_ad_request_service:enabled", valueOf);
        r = rnr.a(0, "gad:force_dynamite_loading_enabled", valueOf);
        rnr.a(0, "gad:dynamite_module:experiment_id");
        rnr.a(1, "gad:http_redirect_max_count:times", 8);
        rnr.a(1, "gads:omid:enabled", valueOf);
        rnr.a(1, "gads:omid:destroy_webview_delay", 1000);
        rnr.a(0, "gads:nonagon:red_button", valueOf);
        rnr.a(1, "gads:nonagon:banner:enabled", valueOf);
        rnr.a(1, "gads:nonagon:banner:ad_unit_exclusions", str2);
        rnr.a(1, "gads:nonagon:interstitial:enabled", valueOf);
        rnr.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", str2);
        rnr.a(1, "gads:nonagon:rewardedvideo:enabled", valueOf);
        rnr.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", valueOf);
        rnr.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", str2);
        rnr.a(1, "gads:nonagon:nativead:enabled", valueOf);
        rnr.a(1, "gads:nonagon:nativead:app_name", str2);
        rnr.a(1, "gads:nonagon:banner:check_dp_size", valueOf);
        rnr.a(1, "gads:nonagon:rewarded:load_multiple_ads", valueOf2);
        rnr.a(1, "gads:nonagon:return_last_error_code", valueOf);
        rnr.a(1, "gads:nonagon:return_no_fill_error_code", valueOf);
        rnr.a(1, "gads:nonagon:open_not_loaded_interstitial", valueOf2);
        rnr.a(1, "gads:nonagon:separate_timeout:enabled", valueOf);
        rnr.a(1, "gads:nonagon:request_timeout:seconds", 60);
        rnr.a(0, "gads:nonagon:limit_ad_request_connection", valueOf2);
        rnr.a(1, "gads:nonagon:service:enabled", valueOf);
        rnr.a(1, "gads:signals:ad_id_info:enabled", valueOf);
        rnr.a(1, "gads:signals:app_index:enabled", valueOf);
        rnr.a(1, "gads:signals:cache:enabled", valueOf);
        rnr.a(1, "gads:signals:doritos:enabled", valueOf);
        rnr.a(1, "gads:signals:doritos:v1:enabled", valueOf);
        rnr.a(1, "gads:signals:location:enabled", valueOf);
        rnr.a(1, "gads:signals:network_prediction:enabled", valueOf);
        rnr.a(1, "gads:signals:parental_control:enabled", valueOf);
        rnr.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
        rnr.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
        rnr.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
        rnr.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
        rnr.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
        rnr.a(0, "gads:rewarded_sku:enabled", valueOf2);
        rnr.a(0, "gads:rewarded_sku:override_test:enabled", valueOf);
        rnr.a(1, "gads:consent:shared_preference_reading:enabled", valueOf2);
        rnr.a(1, "gads:nativeads:image:sample:enabled", valueOf2);
        rnr.a(1, "gads:nativeads:image:sample:pixels", 1048576);
    }
}
