package defpackage;

import java.util.HashMap;
import java.util.Map;

/* renamed from: vqq */
public final class vqq {
    public static final Map a;
    public static final Map b;

    static {
        HashMap hashMap = new HashMap();
        a = hashMap;
        String str = "ASSETURI";
        hashMap.put(str, Integer.valueOf(1));
        String str2 = "CACHEBUSTING";
        a.put(str2, Integer.valueOf(2));
        String str3 = "CONTENTPLAYHEAD";
        a.put(str3, Integer.valueOf(3));
        String str4 = "ERRORCODE";
        a.put(str4, Integer.valueOf(4));
        String str5 = "DISALLOW";
        a.put(str5, Integer.valueOf(5));
        String str6 = "AD_ID";
        a.put(str6, Integer.valueOf(6));
        Map map = a;
        Integer valueOf = Integer.valueOf(51);
        String str7 = "AD_CPN";
        map.put(str7, valueOf);
        String str8 = "AD_LEN";
        a.put(str8, Integer.valueOf(7));
        String str9 = "AD_MT";
        a.put(str9, Integer.valueOf(59));
        String str10 = "AD_SYS";
        a.put(str10, Integer.valueOf(8));
        String str11 = "AD_V";
        a.put(str11, Integer.valueOf(9));
        a.put("BLOCKING_ERROR", Integer.valueOf(10));
        a.put("BREAK_TYPE", Integer.valueOf(11));
        a.put("CONN", Integer.valueOf(12));
        a.put("MT", Integer.valueOf(13));
        a.put("CONTENT_V", Integer.valueOf(14));
        a.put("CPN", Integer.valueOf(15));
        a.put("YT_ERROR_CODE", Integer.valueOf(16));
        a.put("ERROR_MSG", Integer.valueOf(17));
        a.put("EL", Integer.valueOf(18));
        a.put("FORMAT_NAMESPACE", Integer.valueOf(19));
        a.put("FORMAT_SUBTYPE", Integer.valueOf(20));
        a.put("FORMAT_TYPE", Integer.valueOf(21));
        a.put("I_X", Integer.valueOf(22));
        a.put("I_Y", Integer.valueOf(23));
        a.put("INTERNAL_ID", Integer.valueOf(24));
        map = a;
        Integer valueOf2 = Integer.valueOf(25);
        map.put("LACT", valueOf2);
        a.put("MIDROLL_POS", Integer.valueOf(26));
        a.put("P_H", Integer.valueOf(27));
        a.put("VIS", Integer.valueOf(28));
        a.put("P_W", Integer.valueOf(29));
        a.put("RWT", Integer.valueOf(30));
        a.put("SDKV", Integer.valueOf(31));
        a.put("SLOT_POS", Integer.valueOf(32));
        a.put("VOL", Integer.valueOf(33));
        map = a;
        Integer valueOf3 = Integer.valueOf(34);
        map.put("WT", valueOf3);
        String str12 = str11;
        a.put("FILLED_OPPORTUNITY", Integer.valueOf(35));
        a.put("NIELSEN_DEVICE_ID", Integer.valueOf(36));
        a.put("NIELSEN_OS", Integer.valueOf(37));
        a.put("NIELSEN_OS_VERSION", Integer.valueOf(38));
        a.put("NIELSEN_TYPE", Integer.valueOf(39));
        a.put("NIELSEN_PLATFORM", Integer.valueOf(40));
        a.put("NIELSEN_APP_VERSION", Integer.valueOf(41));
        a.put("COMSCORE_TYPE", Integer.valueOf(42));
        a.put("COMSCORE_OS", Integer.valueOf(43));
        a.put("COMSCORE_MODEL", Integer.valueOf(44));
        a.put("COMSCORE_DEVICE_ID", Integer.valueOf(45));
        a.put("POSITION", Integer.valueOf(46));
        a.put("INDEX", Integer.valueOf(47));
        a.put("START", Integer.valueOf(48));
        a.put("VIEWABILITY", Integer.valueOf(49));
        a.put("VSS_AD_CMT", Integer.valueOf(50));
        a.put("VSS_AD_CPN", valueOf);
        a.put("VSS_AD_STATE", Integer.valueOf(52));
        a.put("VSS_AD_RT", valueOf3);
        a.put("VSS_LACT", valueOf2);
        a.put("MOAT_VIEWABILITY", Integer.valueOf(60));
        a.put("GOOGLE_VIEWABILITY", Integer.valueOf(62));
        a.put("IAS_VIEWABILITY", Integer.valueOf(63));
        a.put("DV_VIEWABILITY", Integer.valueOf(64));
        a.put("CLICK_MS", Integer.valueOf(61));
        a.put("VED", Integer.valueOf(65));
        a.put("DIM", Integer.valueOf(66));
        a.put("NB", Integer.valueOf(67));
        a.put("NX", Integer.valueOf(68));
        a.put("NY", Integer.valueOf(69));
        hashMap = new HashMap();
        b = hashMap;
        String str13 = "";
        hashMap.put(str, str13);
        b.put(str2, str13);
        b.put(str3, str13);
        str = "0";
        b.put(str4, str);
        b.put(str5, str13);
        b.put(str6, str13);
        b.put(str7, str13);
        b.put(str8, str);
        str2 = "-1";
        b.put(str9, str2);
        b.put(str10, str13);
        b.put(str12, str);
        b.put("BLOCKING_ERROR", str);
        b.put("BREAK_TYPE", str);
        b.put("CONN", str);
        b.put("MT", str);
        b.put("CONTENT_V", str13);
        b.put("CPN", str13);
        b.put("YT_ERROR_CODE", str);
        b.put("ERROR_MSG", str13);
        b.put("EL", str13);
        b.put("FORMAT_NAMESPACE", str);
        b.put("FORMAT_SUBTYPE", str);
        b.put("FORMAT_TYPE", str);
        b.put("I_X", Integer.toString(-1));
        b.put("I_Y", Integer.toString(-1));
        b.put("INTERNAL_ID", str);
        b.put("LACT", str2);
        b.put("MIDROLL_POS", str);
        b.put("P_H", Integer.toString(-1));
        b.put("VIS", str);
        b.put("P_W", Integer.toString(-1));
        b.put("RWT", str);
        b.put("SDKV", str13);
        b.put("SLOT_POS", str);
        b.put("VOL", str);
        b.put("WT", str);
        b.put("FILLED_OPPORTUNITY", str);
        b.put("NIELSEN_DEVICE_ID", str13);
        b.put("NIELSEN_OS", str13);
        b.put("NIELSEN_OS_VERSION", str13);
        b.put("NIELSEN_TYPE", str13);
        b.put("NIELSEN_PLATFORM", str13);
        b.put("NIELSEN_APP_VERSION", str13);
        b.put("COMSCORE_TYPE", str13);
        b.put("COMSCORE_OS", str13);
        b.put("COMSCORE_MODEL", str13);
        b.put("COMSCORE_DEVICE_ID", str13);
        b.put("POSITION", str);
        b.put("INDEX", str);
        b.put("START", str);
        b.put("VIEWABILITY", str13);
        b.put("VSS_AD_CMT", str2);
        b.put("VSS_AD_CPN", str13);
        b.put("VSS_AD_STATE", str13);
        b.put("VSS_CMT", str2);
        b.put("VSS_CPN", str13);
        b.put("VSS_STATE", str13);
        b.put("VSS_CONN", str);
        b.put("VSS_RT", str);
        b.put("VSS_VIS", str);
        b.put("VSS_AD_RT", str);
        b.put("VSS_LACT", str2);
        b.put("MOAT_VIEWABILITY", str13);
        b.put("GOOGLE_VIEWABILITY", str13);
        b.put("IAS_VIEWABILITY", str13);
        b.put("DV_VIEWABILITY", str13);
        b.put("CLICK_MS", str13);
        b.put("VED", str13);
        b.put("DIM", str13);
        b.put("NB", str13);
        b.put("NX", str13);
        b.put("NY", str13);
    }
}
